# config/config.yaml (Improved Version - Minimal Comments)

app_settings:
  monitoring_interval_s: 30
  purchase_readiness_interval_s: 15
  stealth_level: "STANDARD" # MINIMAL, STANDARD, AGGRESSIVE, PARANOID
  tls_fingerprint_profile: "mac_chrome136_nl_actual"
  enable_persistent_storage: true
  persistent_storage_base_dir: "/Users/macbookpro_ronald/Documents/Personal/Projects/bruce_springsteen_monitor/storage/profiles" # Absolute path to avoid confusion
  golden_profile_name_1: "P03_MacOS_Chrome136_M4Pro_NL" 
  main_purchase_url: "https://www.fansale.it/fansale/member/myfansale.htm"

paths:
  browser_profiles_yaml: "config/browser_profiles.yaml"
  stealth_init_js: "src/core/stealth_init.js"

proxy:
  enabled: true
  username_env: "IPROYAL_USERNAME"
  password_env: "IPROYAL_PASSWORD"
  server_template: "http://{user}:{proxy_pass}@geo.iproyal.com:{port}" # Changed {pass} to {proxy_pass}
  rotating_ports:
    - 12321
    # - 12322
    # - 12323

browser_launch_options:
  browser_type: "chromium"
  channel: "chrome" 
  # executable_path: "/path/to/your/chrome" # Set if Playwright can't find browser
  headless: false # false for UI, true for background
  args:
    - "--disable-blink-features=AutomationControlled"
    - "--disable-infobars"
    - "--window-position=0,0"
    - "--no-first-run"
    - "--no-sandbox" # WARNING: Use with caution
    - "--disable-dev-shm-usage"
  launch_timeout_ms: 90000
  navigation_timeout_ms: 30000
  default_timeout_ms: 30000
  purchase_navigation_timeout_ms: 90000
  purchase_default_timeout_ms: 60000
  use_persistent_user_data_dir_if_available: true 

browser_context_options: # Options for Browser.new_context()
  ignore_https_errors: true # WARNING: Use with caution

browser_pool:
  target_size: 2
  min_size: 1
  max_size: 5
  maintenance_interval_s: 30
  browser_max_age_seconds: 3600 # 1 hour
  browser_max_detections: 3

logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file_path: "logs/ticket_bot.log" # Ensure this directory exists and is writable
  # log_to_console: true # Handled by logger setup, this is just a note

notifications: # Placeholder for notification system integration
  console_alerts: true
  # email_alerts: false
  # pushover_user_key_env: "PUSHOVER_USER_KEY"
  # pushover_api_token_env: "PUSHOVER_API_TOKEN"

targets:
  - platform: "FanSale"
    golden_profile_name_1: "P03_MacOS15_Chrome125_M4Pro_NL"
    url: "https://www.fansale.it/login.htm?forwardUrl=https%3A%2F%2Fwww.fansale.it%2FforwardToReferer.htm%3F404_new"
    enabled: true
    desired_sections: [] # Empty means any availability
    # Optional overrides for specific platform selectors:
    # fansale_no_tickets_selectors: ["custom_no_ticket_selector"]
    # fansale_buy_selectors: ["custom_buy_button_selector"]

  - platform: "Ticketmaster"
    event_name: "Bruce Springsteen Milan July 3 2025"
    url: "https://shop.ticketmaster.it/tickets/bruce-springsteen-and-the-e-street-band-2024-world-tour-03-july-2025-stadio-san-siro-milano-9670.html"
    enabled: true
    desired_sections: []
    # ticketmaster_offer_selector: "custom_offer_selector"

  - platform: "Vivaticket"
    event_name: "Bruce Springsteen Vivaticket Resale"
    url: "https://shop.vivaticket.com/index.php?nvpg[resell]&cmd=tabellaPrezziRivendita&pcode=11787547&tcode=vt0002526"
    enabled: true
    desired_sections: []