# StealthMaster Ultimate Configuration
# Simple, clean configuration for stealthmaster_ultimate.py

targets:
  - platform: fansale
    enabled: true
    url: "https://www.fansale.it/fansale/tickets/all/bruce-springsteen/458554/17844388"
    
    # Login credentials (loaded from .env if available)
    email: ""                           # Leave empty to use FANSALE_EMAIL from .env
    password: ""                        # Leave empty to use FANSALE_PASSWORD from .env
    
    # Auto-reserve settings
    auto_reserve: true                  # Automatically reserve tickets when found
    max_price: 500                      # Maximum price in EUR
    quantity: 1                         # Number of tickets to reserve
    
    # Performance settings
    check_interval: 5                   # Seconds between checks (lower = faster)
    headless: true                      # Run without GUI (faster, less CPU)
    minimize_bandwidth: true            # Block images/CSS (saves 80-90% data)
    
    # Proxy (optional - leave null if not using proxy)
    proxy: null                         # Format: "http://username:password@proxy:port"