# StealthMaster Configuration
# Configuration for the ticket reservation bot

target:
  # The URL of the event page to monitor
  url: "https://www.fansale.it/fansale/tickets/all/bruce-springsteen/458554/17844388"

browser:
  # Run in headless mode (no GUI) - faster but harder to debug
  headless: false
  # Browser window size [width, height]
  window_size: [1280, 720]

monitoring:
  # Time in seconds between page checks
  check_interval: 5
  # Maximum number of tickets to reserve
  max_tickets: 4
  
# Note: All credentials (email, password, proxy, etc.) should be in .env file