# Simplified StealthMaster Config - No BS Edition

app_settings:
  mode: "simple"  # Just one mode that works
  dry_run: false
  
# Proxy settings (currently disabled to avoid blocks)
proxy_settings:
  enabled: false  # Turn on when you find proxies that work
  primary_pool:
    - host: "geo.iproyal.com"
      port: 12321
      username: "${PROXY_USERNAME}"
      password: "${PROXY_PASSWORD}"
      type: "http"

# Authentication (if needed for auto-login)
authentication:
  enabled: false
  platforms:
    fansale:
      username: "${FANSALE_USERNAME}"
      password: "${FANSALE_PASSWORD}"

# Monitoring targets
targets:
  # FANSALE - Bruce Springsteen Milano
  - platform: "fansale"
    event_name: "Bruce Springsteen Milano 2025"
    url: "https://www.fansale.it/fansale/tickets/all/bruce-springsteen/458554/17844388"
    enabled: true
    interval_s: 30  # Check every 30 seconds
    
  # Add more events here when needed
  # - platform: "fansale"
  #   event_name: "Another Event"
  #   url: "https://..."
  #   enabled: true
  #   interval_s: 30

# Simple notification settings
notifications:
  console_alerts: true
  sound_alerts: true
  log_file: "tickets_found.log"

# Basic logging
logging:
  level: "INFO"
  log_directory: "logs"
  main_log_file: "monitor.log"
