# config/config.yaml - StealthMaster AI v2.0
# Revolutionary configuration for ultra-stealth ticket acquisition

# =============================================================================
# APPLICATION SETTINGS
# =============================================================================
app_settings:
  mode: "adaptive"  # Options: stealth, beast, ultra_stealth, adaptive, hybrid
  version: "2.0.0"
  dry_run: false
  browser_open_mode: "both"  # default, automated, both
  
  # Mode-specific optimizations
  mode_configs:
    ultra_stealth:
      max_concurrent_monitors: 1
      max_concurrent_strikes: 1
      max_connections: 20
      cache_size: 500
      profile_rotation_interval: 300
      min_quality_tier: 5
      
    stealth:
      max_concurrent_monitors: 2
      max_concurrent_strikes: 2
      max_connections: 30
      cache_size: 750
      profile_rotation_interval: 180
      min_quality_tier: 4
      
    adaptive:
      max_concurrent_monitors: 3
      max_concurrent_strikes: 3
      max_connections: 50
      cache_size: 1000
      # Adaptive mode adjusts dynamically
      
    hybrid:
      max_concurrent_monitors: 4
      max_concurrent_strikes: 4
      max_connections: 75
      cache_size: 1500
      min_quality_tier: 3
      
    beast:
      max_concurrent_monitors: 8
      max_concurrent_strikes: 10
      max_connections: 100
      cache_size: 2000
      min_quality_tier: 1

# =============================================================================
# MONITORING SETTINGS
# =============================================================================
monitoring_settings:
  default_interval_s: 30
  min_monitor_interval_s: 3
  cache_max_age_s: 300
  
  # Quantum optimization
  quantum_optimization:
    enabled: true
    pattern_analysis_interval: 60
    resource_reallocation: true
    predictive_burst_mode: true

# =============================================================================
# BROWSER OPTIONS
# =============================================================================
browser_options:
  headless: false  # IMPORTANT: Set to false to see browsers
  channel: "chrome"  # Use real Chrome for better compatibility
  
  # StealthMaster AI enhancements
  stealth_options:
    viewport_randomization: true
    timezone_spoofing: true
    webgl_noise: true
    canvas_fingerprint_defender: true
    audio_context_noise: true
    font_fingerprint_defender: true
    
  # Advanced evasion
  cdp_evasion:
    enabled: true
    runtime_enable_bypass: true
    console_hook_bypass: true
    error_stack_cleaning: true

# =============================================================================
# STRIKE FORCE SETTINGS
# =============================================================================
strike_settings:
  coordination_strategy: "quantum"  # quantum, parallel, sequential
  profile_selection: "ml_optimized"  # ml_optimized, round_robin, random
  
  timeout_configs:
    navigation: 30000
    strike_execution: 45000
    queue_wait: 300000
    
  success_indicators:
    - "reservation successful"
    - "added to cart"
    - "order confirmed"
    - "pagamento"
    - "conferma"

# =============================================================================
# AUTHENTICATION
# =============================================================================
authentication:
  enabled: true
  
  platforms:
    fansale:
      username: "${FANSALE_EMAIL}"
      password: "${FANSALE_PASSWORD}"
      
    # Uncomment and configure if you have Ticketmaster credentials
    # ticketmaster_it:
    #   username: "${TM_USERNAME}"
    #   password: "${TM_PASSWORD}"
      
    # Uncomment and configure if you have Vivaticket credentials
    # vivaticket_it:
    #   username: "${VIVATICKET_USERNAME}"
    #   password: "${VIVATICKET_PASSWORD}"

# =============================================================================
# PROXY CONFIGURATION - CRITICAL FOR STEALTH
# =============================================================================
proxy_settings:
  enabled: true
  rotation_strategy: "intelligent"  # intelligent, round_robin, random
  
  # Primary proxy pool (IPRoyal residential)
  primary_pool:
    - host: "${IPROYAL_HOSTNAME}"
      port: ${IPROYAL_PORT}
      username: "${IPROYAL_USERNAME}"
      password: "${IPROYAL_PASSWORD}"
      type: "http"
      country: "IT"
      quality_score: 0.95
      provider: "iproyal"
      
    # Add more IPRoyal endpoints if you have them
    # - host: "${IPROYAL_HOSTNAME2}"
    #   port: ${IPROYAL_PORT2}
    #   username: "${IPROYAL_USERNAME2}"
    #   password: "${IPROYAL_PASSWORD2}"
    #   type: "http"
    #   country: "IT"
    #   quality_score: 0.90
    #   provider: "iproyal"
  
  # Backup pool (if you have other providers)
  backup_pool: []
    # - host: "${BACKUP_PROXY_HOST}"
    #   port: ${BACKUP_PROXY_PORT}
    #   username: "${BACKUP_PROXY_USER}"
    #   password: "${BACKUP_PROXY_PASS}"
    #   type: "http"
    #   country: "DE"
    #   quality_score: 0.70
  
  # Proxy rotation rules
  rotation_rules:
    rotate_on_block: true
    rotate_interval_minutes: 30
    max_requests_per_proxy: 100
    cooldown_after_block_minutes: 120
    
  # Platform-specific proxy preferences
  platform_preferences:
    fansale:
      preferred_countries: ["IT", "CH", "AT"]  # Italian-speaking regions
      require_residential: true
    ticketmaster:
      preferred_countries: ["IT", "EU"]
      require_residential: true
    vivaticket:
      preferred_countries: ["IT"]
      require_residential: false  # Less strict
      
  # Proxy validation
  validation:
    test_url: "https://httpbin.org/ip"
    timeout_seconds: 10
    validate_on_start: true
    revalidate_interval_hours: 6

# =============================================================================
# PROFILE MANAGEMENT
# =============================================================================
profile_settings:
  profile_count: 50  # Total profiles to maintain
  rotation_strategy: "performance_based"
  
  # Profile-Proxy binding
  proxy_binding:
    enabled: true
    sticky_sessions: true  # Keep same proxy per profile
    rotation_sync: true    # Rotate proxy when rotating profile
  
  quality_distribution:
    premium: 10  # Tier 5 profiles
    high: 15     # Tier 4 profiles
    medium: 15   # Tier 3 profiles
    standard: 10 # Tier 1-2 profiles
    
  fingerprint_mutation:
    enabled: true
    mutation_interval: 3600  # 1 hour
    mutation_factor: 0.15

# =============================================================================
# DATA OPTIMIZATION
# =============================================================================
data_limits:
  global_limit_mb: 10000
  session_limit_mb: 2000
  
  optimization_thresholds:
    aggressive_trigger_percent: 70
    emergency_trigger_percent: 90
    
  resource_blocking:
    images: true
    media: true
    fonts: true
    trackers: true
    analytics: true

# =============================================================================
# TICKETING TARGETS
# =============================================================================
targets:
  # FANSALE - Bruce Springsteen Milano
  - platform: "fansale"
    event_name: "Bruce Springsteen Milano 2025"
    url: "https://www.fansale.it/fansale/tickets/all/bruce-springsteen/458554/17844388"
    enabled: true
    priority: "CRITICAL"
    interval_s: 20
    
    # Ticket preferences
    desired_sections: ["Prato", "Tribuna", "Primo Anello"]
    max_price_per_ticket: 800
    min_ticket_quantity: 2
    max_ticket_quantity: 4
    fair_deal_only: false
    certified_only: false
    
    # Burst mode for high activity
    burst_mode:
      enabled: true
      min_interval_s: 3
      duration_s: 300
      trigger_on_activity: true
      
  # TICKETMASTER - Bruce Springsteen San Siro
  - platform: "ticketmaster"
    event_name: "Bruce Springsteen San Siro 2025"
    url: "https://shop.ticketmaster.it/biglietti/bruce-springsteen-2025-milano"
    enabled: true
    priority: "CRITICAL"
    interval_s: 25
    
    desired_sections: ["Floor", "Lower Bowl", "Club"]
    max_price_per_ticket: 750
    min_ticket_quantity: 2
    max_ticket_quantity: 4
    
    # Queue handling
    queue_config:
      auto_join: true
      maintain_presence: true
      multi_tab_protection: false
      
  # VIVATICKET - Bruce Springsteen (if available)
  - platform: "vivaticket"
    event_name: "Bruce Springsteen Tour 2025"
    url: "https://www.vivaticket.com/it/search?q=bruce+springsteen"
    enabled: false  # Enable when tickets available
    priority: "HIGH"
    interval_s: 30
    
    desired_sections: []  # Any section
    max_price_per_ticket: 600
    min_ticket_quantity: 1
    max_ticket_quantity: 4

# =============================================================================
# ANTI-DETECTION MEASURES
# =============================================================================
anti_detection:
  # Behavioral simulation
  human_simulation:
    mouse_movements: true
    keyboard_typing: true
    scroll_patterns: true
    reading_delays: true
    micro_movements: true
    
  # Network behavior
  request_patterns:
    randomize_intervals: true
    vary_user_agents: true
    rotate_headers: true
    
  # Recovery strategies
  block_recovery:
    profile_rotation: true
    cooldown_multiplier: 2.0
    max_retries: 3

# =============================================================================
# LOGGING
# =============================================================================
logging:
  level: "INFO"
  log_directory: "logs"
  main_log_file: "stealthmaster.log"
  error_log_file: "errors.log"
  
  # Enhanced logging
  performance_logging:
    enabled: true
    log_file: "performance.log"
    
  detection_logging:
    enabled: true
    log_file: "detection_events.log"
    
  ticket_logging:
    enabled: true
    log_file: "ticket_opportunities.log"

# =============================================================================
# ADVANCED FEATURES
# =============================================================================
advanced_features:
  # Machine learning optimization
  ml_optimization:
    enabled: true
    model_update_interval: 3600
    feature_extraction: true
    
  # Quantum coordination
  quantum_coordination:
    enabled: true
    entanglement_factor: 0.8
    superposition_states: 3
    
  # Predictive analytics
  predictive_analytics:
    enabled: true
    pattern_recognition: true
    demand_forecasting: true
    
  # Emergency protocols
  emergency_protocols:
    auto_switch_ultra_stealth: true
    threat_threshold: 0.8
    emergency_cooldown: 600