#/config/config.yaml
# -----------------------------------------------------------------------------
# APPLICATION SETTINGS
# -----------------------------------------------------------------------------
app_settings:
  mode: "adaptive" # Options: "stealth", "beast", "hybrid", "adaptive", "ultra_stealth"
  version: "2.0.1"
  dry_run: false
  browser_open_mode: "both" # Options: "default" (system browser), "automated" (playwright), "both"

  mode_configs:
    stealth:
      strike_settings:
        max_parallel: 1
      monitoring_settings:
        base_target_interval_multiplier: 1.5
      profile_manager:
        selection_quality_min_tier: 4
    beast:
      strike_settings:
        max_parallel: 5

      profile_manager:
        selection_quality_min_tier: 2
    ultra_stealth:
      strike_settings:
        max_parallel: 1
      monitoring_settings:
        base_target_interval_multiplier: 2.0
      profile_manager:
        selection_quality_min_tier: 5
    adaptive:
      pass
    hybrid: {}
  
# -----------------------------------------------------------------------------
# MONITORING SETTINGS (MOVED TO TOP LEVEL)
# This section is read by ProfileAwareLightweightMonitor and main.py's config loader
# -----------------------------------------------------------------------------
monitoring_settings:
  default_interval_s: 60       # Renamed from default_target_interval_s to match ProfileAwareLightweightMonitor's direct expectation
  min_monitor_interval_s: 15
  cache_max_age_s: 300         # Example: How long monitor considers cached items fresh (default in code is 300)
  # detection_patterns:        # You can define platform-specific regex patterns here if needed
  #   fansale:
  #     offers: "your_regex_here" 
  #   ticketmaster:
  #     offers: "your_regex_here"


# -----------------------------------------------------------------------------
# DATA USAGE LIMITS
# -----------------------------------------------------------------------------
data_limits:
  global_limit_mb: 5000
  session_limit_mb: 1000
  optimization_thresholds:
    aggressive_trigger_percent: 80
    emergency_trigger_percent: 95

# -----------------------------------------------------------------------------
# MONITORING TARGETS
# -----------------------------------------------------------------------------
targets:
  - platform: "fansale"
    event_name: "Bruce Springsteen Milano 2025 (FS)"
    url: "https://www.fansale.it/fansale/tickets/all/bruce-springsteen/458554/17844388"
    enabled: true
    priority: "CRITICAL" # CRITICAL, HIGH, NORMAL, LOW
    interval_s: 30
    human_behavior_intensity: "medium" # low, medium, high, none
    desired_sections: []
    max_price_per_ticket: 600
    min_ticket_quantity: 1
    max_ticket_quantity: 4
    burst_mode:
      enabled: true
      min_interval_s: 3
      duration_s: 300

  - platform: "ticketmaster"
    event_name: "Bruce Springsteen San Siro 2025 (TM)"
    url: "https://shop.ticketmaster.it/biglietti/bruce-springsteen-and-the-e-street-band-2024-world-tour-03-luglio-2025-stadio-san-siro-milano-9670.html"
    enabled: true
    priority: "HIGH"
    interval_s: 45
    human_behavior_intensity: "low"
    desired_sections: []
    max_price_per_ticket: 300.00
    burst_mode:
      enabled: true
      min_interval_s: 5
      duration_s: 240

  - platform: "vivaticket"
    event_name: "Bruce Springsteen Resale (VT)"
    url: "https://shop.vivaticket.com/it/ricerca/bruce%20springsteen"
    enabled: true
    priority: "NORMAL"
    interval_s: 90
    human_behavior_intensity: "low"
    desired_sections: []
    max_price_per_ticket: 400.00
    burst_mode:
      enabled: false

# -----------------------------------------------------------------------------
# NETWORK CONFIGURATION
# -----------------------------------------------------------------------------
network:
  max_connections_per_host: 20
  max_keepalive_connections: 10
  connect_timeout_seconds: 10
  read_timeout_seconds: 15
  http2_enabled: true
  max_reuse_per_connection: 100

# -----------------------------------------------------------------------------
# CACHE CONFIGURATION
# -----------------------------------------------------------------------------
cache:
  max_size_mb: 50
  default_ttl_seconds: 120

# -----------------------------------------------------------------------------
# BROWSER LAUNCH & CONTEXT DEFAULTS
# -----------------------------------------------------------------------------
browser_options:
  headless: false  # CHANGED: Show browsers for user visibility
  default_launch_args:
    - "--disable-blink-features=AutomationControlled"
    - "--disable-web-security"
    - "--disable-features=VizDisplayCompositor"
    - "--start-maximized"  # Start browsers maximized
    - "--no-first-run"
    - "--disable-default-apps"
  default_context_options:
    java_script_enabled: true
    accept_downloads: true
  default_page_timeout_ms: 30000
  default_navigation_timeout_ms: 45000

browser_instance_pool:
  target_size: 3
  min_size: 1
  max_size: 5
  browser_max_age_seconds: 1800
  browser_max_detections: 3
  browser_health_threshold: 40.0
  critical_health_threshold: 20.0
  browser_quarantine_seconds: 300
  maintenance_interval_s: 30
  adaptive_pool_sizing: true

# -----------------------------------------------------------------------------
# STRIKE CONFIGURATION
# -----------------------------------------------------------------------------
strike_settings:
  max_parallel: 3
  timeout_s: 30

# -----------------------------------------------------------------------------
# PROFILE MANAGER CONFIGURATION (for ProfileManager in src/profiles/manager.py)
# This should align with your ProfileManagerConfig dataclass
# -----------------------------------------------------------------------------
profile_manager:
  num_target_profiles: 15 # Reduced for faster startup
  profiles_per_platform: 3 # Reduced for faster startup
  evolution_interval_seconds: 1800 # Increased interval
  persistence_filepath: "profiles_backup.json"
  session_backup_dir: "session_backups"
  enable_encrypted_storage: true
  lazy_loading: true # Enable lazy loading
  # compromise_threshold_pct, min_pool_size_for_replacement, etc. are in ProfileManagerConfig defaults

  # scoring_config: # Fields for ProfileScoringConfig
  #   base_score: 100.0
  #   state_modifiers: { PRISTINE: 20.0, HEALTHY: 30.0, ... }

  # cooldowns_seconds: # Fields for cooldowns
  #   HARD_BLOCK: [14400, 0.3]

  # --- Proxy settings (if ProfileManagerConfig expects proxy_configs list) ---
  proxies: # <--- THIS is the key the parser looks for
  - proxy_type: "http"
    host: "${IPROYAL_HOSTNAME}"
    port: ${IPROYAL_PORT}
    username: "${IPROYAL_USERNAME}"
    password: "${IPROYAL_PASSWORD}"
    country_code: "IT"
    sticky_session: true
    provider: "iproyal"

  # --- Flags that should be in ProfileManagerConfig in src/profiles/config.py ---
  enable_tls_rotation: true
  enable_behavioral_warmup: true
  enable_session_preloading: true
  warmup_sites:
    - "https://www.google.it"
    - "https://www.repubblica.it"
    - "https://www.corriere.it"
    - "https://www.amazon.it"

# -----------------------------------------------------------------------------
# BEHAVIORAL SIMULATION
# -----------------------------------------------------------------------------
behavioral_simulation:
  enabled: true
  defaults:
    typing_speed_wpm_range: [40, 75]
    mouse_acceleration_range: [1.0, 1.8]
    scroll_velocity_preference_range: [300, 700]
    click_dwell_time_ms_range: [70, 140]
    movement_jitter_factor_range: [0.04, 0.12]
    pause_between_actions_s_range: [0.4, 1.5]
    reading_speed_wpm_range: [200, 320]
    attention_span_seconds_range: [15, 40]
    multitasking_tendency_range: [0.15, 0.55]
  platform_intensity_hints:
    fansale: "medium"
    ticketmaster: "high"
    vivaticket: "low"

# -----------------------------------------------------------------------------
# EVASION SETTINGS
# -----------------------------------------------------------------------------
evasion_settings:
  webrtc:
    mode: "default_public_interface_only"

# -----------------------------------------------------------------------------
# AUTHENTICATION
# -----------------------------------------------------------------------------
authentication:
  enabled: true  # CHANGED: Enable authentication
  platforms:
    fansale:  # ADDED: FanSale authentication
      username: "${FANSALE_EMAIL}"
      password: "${FANSALE_PASSWORD}"
    # ticketmaster_it:
    #   username: "${TM_USERNAME}"
    #   password: "${TM_PASSWORD}"
    # vivaticket_it: # If Vivaticket has direct login you manage
    #   username: "${VIVATICKET_USERNAME}" # Define in .env
    #   password: "${VIVATICKET_PASSWORD}" # Define in .env

# -----------------------------------------------------------------------------
# PATHS
# -----------------------------------------------------------------------------
paths:
  stealth_script: "src/core/stealth_init.js"

# -----------------------------------------------------------------------------
# LOGGING (Separate from app_settings for clarity, used by main.py's setup_logging)
# -----------------------------------------------------------------------------
logging:
  level: "INFO" # Root logger level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_directory: "logs" # Overrides app_settings.logging.log_directory if main.py prioritizes this
  main_log_file: "ticket_system.log"
  error_log_file: "errors.log"
  # Enhanced logging options
  log_ticket_detections: true  # Log all ticket detections to separate file
  ticket_log_file: "ticket_detections.log"
  log_performance_metrics: true  # Log performance metrics periodically
  performance_log_file: "performance.log"
  # log_max_file_size_mb: 10 # These could be here too
  # log_backup_count: 5